import assert from 'node:assert/strict';
import fs from 'node:fs';

const game=fs.readFileSync(new URL('../docs/src/engine/game.js',import.meta.url),'utf8');
const alloc=game.slice(game.indexOf('function allocUI'),game.indexOf('function nextStep'));
for(const text of ["'すべてリセット'",'beforeTouched','sessionStart','beforeDiceIndex'])assert.match(alloc,new RegExp(text));
assert.doesNotMatch(alloc,/abrow-actions|data-alloc-action|\['\+1'|'\+5'|'MAX'/);
assert.doesNotMatch(game,/actualAbilitySpend|pointsRequiredToReach80|ability-allocation-policy/);
assert.match(alloc,/const spend=dice\?dice\[idx\]:1/);
assert.match(alloc,/r\.onclick=allocate/);
assert.match(alloc,/event\.key==='Enter'\|\|event\.key===' '/);
assert.match(alloc,/aria-disabled/);
assert.match(alloc,/restoreTouched\(entry\.beforeTouched\)/);
assert.match(alloc,/restoreTouched\(sessionStart\.touchedKeys\)/);
assert.match(alloc,/idx=sessionStart\.diceIndex/);
assert.match(alloc,/hist=\[\];render\(\);board\(0\)/);
assert.match(alloc,/reset\.disabled=!hist\.length/);
assert.doesNotMatch(alloc,/\b(?:R|ri|pick|chance)\s*\(/);
assert.match(game,/cur>=66\?7:cur>=60\?4:cur>=55\?2:1/);
assert.match(game,/if\(cur>=pk\)cost\*=isP\?4:3/);
console.log('Ability allocation v1.6.1 checks passed.');
