import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {runInNewContext} from 'node:vm';
import {JP_DATA} from '../docs/src/data/jp-data.js';
import * as champ from '../docs/src/engine/championship-policy.js';
import * as intl from '../docs/src/engine/international-trait-policy.js';
import * as contracts from '../docs/src/engine/contract-policy.js';
import {applyIncentivePayment,createIncentiveTerms} from '../docs/src/engine/incentive-policy.js';
import {classifyMarketInjury} from '../docs/src/engine/injury-market-policy.js';
const game=readFileSync(new URL('../docs/src/engine/game.js',import.meta.url),'utf8');
const teamById=id=>JP_DATA.teams.find(t=>t.teamId===id);
let cases=0;
function test(name,fn){fn();cases++;console.log('PASS '+name);}
function state(v={}){return {year:2035,stage:'PRO',lv:'NPB1',org:'NPB',orgTeamId:'NPB_CL_HAN',lastD:4,seasonFactor:1,traits:{},honors:[],championshipMigrationVersion:1,championshipResults:{},seasonChampContext:null,seasonEndMaintenanceYear:null,tradeRefuse:0,tradeHeat:0,intlCount:0,intlFinalCount:0,intlTraitResults:{},intlCompletedKeys:{},internationalTraitMigrationVersion:1,intlStat:{G:0,PA:0,AB:0,H:0,HR:0,RBI:0,IP:0,SO:0,ER:0,W:0,SV:0},pool:0,injNext:0,...v};}
for(const [lv,org,p,title] of [['NPB1','NPB',10,'日本一'],['MLB','MLB',3.5,'ワールドシリーズチャンピオン'],['MLB','MiLB',3.5,'ワールドシリーズチャンピオン'],['CPBL1','CPBL',15,'台湾シリーズ優勝'],['KBO1','KBO',10,'韓国シリーズ優勝']])test('C01/C02 '+org+'/'+lv,()=>{const s=state({lv,org,lastD:lv==='NPB1'?4:0,orgTeamId:JP_DATA.teams.find(t=>t.org===(org==='MiLB'?'MLB':org)).teamId});champ.captureSeasonChampionship(s);let calls=0;const first=champ.settleChampionship(s,{teamById,random:()=>{calls++;return 0;}});assert.equal(first.result.chancePercent,p);assert.equal(first.result.title,title);assert.deepEqual(s.honors,[`2035 ${title}`]);const saved=JSON.stringify(s);assert.equal(champ.settleChampionship(s,{teamById,random:()=>{calls++;return 0;}}).created,false);assert.equal(JSON.stringify(s),saved);assert.equal(calls,1);});
for(const [lv,min,max] of [['NPB1',2,15],['MLB',2,9],['CPBL1',2,26],['KBO1',2,20]])for(const d of [-100,100])for(const clutch of [false,true])for(const refuse of [0,2])test('C03 '+[lv,d,clutch,refuse].join('/'),()=>{const org={NPB1:'NPB',MLB:'MLB',CPBL1:'CPBL',KBO1:'KBO'}[lv],s=state({lv,org,lastD:d,traits:{clutch},tradeRefuse:refuse,orgTeamId:JP_DATA.teams.find(t=>t.org===org).teamId});champ.captureSeasonChampionship(s);const p=(d<0?min:max)*(clutch?1.25:1)*(refuse?.75:1);assert.equal(champ.championshipEligibility(s,teamById).chancePercent,p);assert.equal(champ.settleChampionship(s,{teamById,random:()=>p/100}).result.won,false,'strict chance boundary');});
for(const lv of ['NPB2','NPB_DEV','KBO2','CPBL2','R','A1','A2','A3','HS','U','CORP','IND'])test('C04 '+lv,()=>{const s=state({lv});champ.captureSeasonChampionship(s);champ.settleChampionship(s,{teamById,random:()=>assert.fail('ineligible RNG')});assert.equal(s.wonChamp,false);assert.deepEqual(s.honors,[]);});
test('C04 full rehabilitation/invalid team/missing context',()=>{for(const v of [{seasonFactor:0},{orgTeamId:'unknown'},{org:'KBO'}]){const s=state(v);champ.captureSeasonChampionship(s);champ.settleChampionship(s,{teamById,random:()=>assert.fail('invalid RNG')});assert.equal(s.wonChamp,false);}const s=state();assert.equal(champ.settleChampionship(s,{teamById,random:()=>assert.fail()}).result.reason,'MISSING_SEASON_CONTEXT');});
test('C05 failure cache + C07 downgrade + C08 transfer snapshot',()=>{const s=state();champ.captureSeasonChampionship(s);s.lv='NPB2';s.orgTeamId='NPB_PL_FUK';assert.equal(champ.captureSeasonChampionship(s).teamId,'NPB_CL_HAN');champ.settleChampionship(s,{teamById,random:()=>0});assert.equal(s.championshipResults[2035].level,'NPB1');assert.notEqual(s.champThisTeam,true);assert.equal(s.honors[0],'2035 日本一');s.year++;s.champThisTeam=true;s.champTeam=s.orgTeamId;s.lv='NPB1';champ.captureSeasonChampionship(s);let calls=0;champ.settleChampionship(s,{teamById,random:()=>{calls++;return .99;}});champ.settleChampionship(s,{teamById,random:()=>assert.fail()});assert.equal(calls,1);assert.equal(s.champThisTeam,true);assert.equal(s.wonChamp,false);});
test('C10 paid legacy, exact honor, no inferred team',()=>{for(const honors of [[],['2035 日本一']]){const s=state({championshipMigrationVersion:undefined,lastSalaryPaidYear:2035,honors});champ.normalizeChampionshipState(s,teamById);assert.equal(champ.settleChampionship(s,{teamById,random:()=>assert.fail()}).result.reason,'MIGRATED_ALREADY_SETTLED');assert.equal(s.wonChamp,honors.length>0);assert.equal(s.champThisTeam,false);assert.equal(s.champTeam,null);const saved=JSON.stringify(s);champ.normalizeChampionshipState(s,teamById);assert.equal(JSON.stringify(s),saved);}const s=state({championshipMigrationVersion:undefined,ct:{annualSchedule:[{year:2035,paid:true}]}});champ.normalizeChampionshipState(s,teamById);assert.equal(s.championshipResults[2035].eligible,false);});
test('legacy snapshot only from trustworthy structured data',()=>{const s=state({championshipMigrationVersion:undefined,log:[{y:2035,tm:'阪神ストライプス',st:{d:4}}]});champ.normalizeChampionshipState(s,teamById);assert.equal(s.seasonChampContext,null);const t=state({championshipMigrationVersion:undefined,log:[{y:2035,teamId:'NPB_CL_HAN',level:'NPB1',org:'NPB',seasonFactor:1,ratingD:4,clutch:false,tradeRefuse:0}]});champ.normalizeChampionshipState(t,teamById);assert.equal(t.seasonChampContext.teamId,'NPB_CL_HAN');});
test('annual maintenance once, no negative counters',()=>{const s=state({tradeRefuse:2,tradeHeat:7});assert.equal(champ.maintainSeasonEnd(s),true);assert.deepEqual([s.tradeRefuse,s.tradeHeat],[1,2]);assert.equal(champ.maintainSeasonEnd(s),false);s.year++;champ.maintainSeasonEnd(s);assert.deepEqual([s.tradeRefuse,s.tradeHeat],[0,0]);});
const ev={eventKey:'P12:2035',name:'WBSCプレミア12'};
const play=(s,rank,e=ev)=>intl.commitInternationalResult(s,intl.prepareInternationalResult(s,e,{rank,stats:{...s.intlStat,G:s.intlStat.G+5},hadIntlace:Boolean(s.traits.intlace)}));
test('I01 third finalist unlock, ordinary reward/fatigue',()=>{const s=state({intlCount:2,intlFinalCount:1});const r=play(s,'準優勝').result;assert.equal(r.unlockedIntlace,true);assert.deepEqual([s.intlCount,s.intlFinalCount,s.pool,s.injNext],[3,2,5,10]);});
test('I02 third best8 unlock; next best8 minimum2',()=>{const s=state({intlCount:2,intlFinalCount:2});play(s,'ベスト8');assert.deepEqual([s.pool,s.injNext],[1,10]);assert.equal(s.traits.intlace,true);play(s,'ベスト8',{...ev,eventKey:'WBC:2038'});assert.deepEqual([s.pool,s.injNext],[3,10]);});
test('I03 top4 not a final',()=>{const s=state({intlCount:3,intlFinalCount:1});play(s,'ベスト4');assert.equal(s.intlFinalCount,1);assert.notEqual(s.traits.intlace,true);});
for(const [rank,points] of [['優勝',7],['準優勝',5],['ベスト4',3],['ベスト8',2]])test('I04/I05/I06 '+rank,()=>{const s=state({traits:{intlace:true},injNext:17});const prepared=intl.prepareInternationalResult(s,ev,{rank,stats:{...s.intlStat,G:5},hadIntlace:true});intl.commitInternationalResult(s,prepared);assert.equal(s.pool,points);assert.equal(s.injNext,17);const saved=JSON.stringify(s);assert.equal(intl.commitInternationalResult(s,prepared).created,false);assert.equal(JSON.stringify(s),saved);});
test('I05 fatigue retains other causes',()=>{const s=state({injNext:17});play(s,'ベスト8');assert.equal(s.injNext,27);});
test('I09/I10 migration exact honors, max not sum, preserve trait/count',()=>{const s=state({internationalTraitMigrationVersion:undefined,intlFinalCount:undefined,intlTop4:2,intlCount:3,honors:['2030 ワールド・ベースボール・クラシック優勝','2030 ワールド・ベースボール・クラシック準優勝','2031 WBSCプレミア12準優勝','2031 WBSCプレミア12準優勝MVP','2035 日本一','2034 ワールド・ベースボール・クラシックベスト4'],intlCompletedKeys:{a:true,b:true,c:true,d:true}});intl.normalizeInternationalState(s);assert.deepEqual([s.intlCount,s.intlFinalCount,s.pool,s.injNext],[3,2,0,0]);assert.equal(s.traits.intlace,true);const saved=JSON.stringify(s);intl.normalizeInternationalState(s);assert.equal(JSON.stringify(s),saved);const t=state({internationalTraitMigrationVersion:undefined,intlFinalCount:undefined,intlCount:'bad',intlTop4:'bad',intlCompletedKeys:{a:true,b:true,c:true}});intl.normalizeInternationalState(t);assert.deepEqual([t.intlCount,t.intlFinalCount],[0,0]);});
test('structured result overrides ambiguous honor, valid final count retained',()=>{const s=state({internationalTraitMigrationVersion:undefined,intlFinalCount:undefined,honors:['2035 WBSCプレミア12優勝'],intlTraitResults:{'P12:2035':{eventKey:'P12:2035',rank:'ベスト4'}}});intl.normalizeInternationalState(s);assert.equal(s.intlFinalCount,0);const t=state({internationalTraitMigrationVersion:undefined,intlFinalCount:1,honors:['2030 ワールド・ベースボール・クラシック優勝','2031 WBSCプレミア12優勝']});intl.normalizeInternationalState(t);assert.equal(t.intlFinalCount,1);});
// Execute the actual active international functions, not a reimplementation.
function activeIntl(v={},source=game){
  const s=state({ab:{vel:65,ctl:65,brk:65,sta:65},pos:'P',role:'SP',rehab:0,skipMid:false,seasonFactor:1,intlDeclinedCount:0,...v});let opts,draws=0,done=0,cards=[];
  const context={...intl,S:s,DATA:JP_DATA,ovr:()=>65,clamp:(x,a,b)=>Math.max(a,Math.min(b,x)),ri:(a,b)=>{draws++;return a;},R:()=>{draws++;return .1;},chance:()=>{draws++;return false;},pick:a=>{draws++;return a[context.rank||0];},isSP:()=>true,choose:(_,o)=>{opts=o;},card:(...a)=>cards.push(a),displayTrait:()=> '国際大会の鬼',nextStep:()=>{},maybeIntl:null};
  runInNewContext(source.slice(source.indexOf('  function intlEvents('),source.indexOf('  maybeIntl = function(done)')),context);
  return {s,context,run:phase=>context.processIntlPhase(phase,()=>done++),options:()=>opts,report:()=>({draws,done,cards})};
}
test('I06 actual accepted callback twice: stats/RNG/rewards/next once',()=>{const f=activeIntl({intlCount:2,intlFinalCount:1});f.context.rank=1;f.run('POST');const button=f.options()[0];button.f();const saved=JSON.stringify(f.s),report=JSON.stringify(f.report());button.f();assert.equal(JSON.stringify(f.s),saved);assert.equal(JSON.stringify(f.report()),report);assert.equal(f.s.intlCount,3);assert.equal(f.s.intlFinalCount,2);assert.equal(f.report().done,1);assert.equal(f.report().cards.length,2);});
test('I07 actual denied/injured/declined no reward/RNG',()=>{for(const v of [{lv:'NPB2'},{rehab:1},{skipMid:true},{seasonFactor:.5},{}]){const f=activeIntl(v);f.run('POST');if(f.options()){const b=f.options()[1];b.f();b.f();}assert.equal(f.s.intlCount,0);assert.equal(f.s.pool,0);assert.equal(f.s.injNext,0);assert.equal(f.report().draws,0);assert.equal(f.report().done,1);assert.equal(f.s.intlCompletedKeys['P12:2035'],true);}});
test('I08 same-year PRE/POST, next event gets newly unlocked effect',()=>{const f=activeIntl({year:2035,intlCount:2,intlFinalCount:2});f.context.DATA={...JP_DATA,intlEvents:[{eventKey:'WBC:2035',name:'ワールド・ベースボール・クラシック',startDate:'2035-03-05'},{eventKey:'P12:2035',name:'WBSCプレミア12',startDate:'2035-11-10'}]};f.context.rank=3;f.run('PRE');f.options()[0].f();assert.equal(f.s.traits.intlace,true);f.run('POST');f.options()[0].f();assert.deepEqual([f.s.pool,f.s.injNext,f.s.intlCount],[3,10,4]);});
test('international result UI failure can redraw without RNG/recommit',()=>{const f=activeIntl();f.run('POST');const b=f.options()[0],card=f.context.card;f.context.card=()=>{throw Error('UI fixture');};assert.throws(()=>b.f(),/UI fixture/);const saved=JSON.stringify(f.s),draws=f.report().draws;f.context.card=card;b.f();assert.equal(JSON.stringify(f.s),saved);assert.equal(f.report().draws,draws);assert.equal(f.report().done,1);});
test('unlock UI retry does not duplicate already rendered result',()=>{const f=activeIntl({intlCount:2,intlFinalCount:2});f.run('POST');const b=f.options()[0],card=f.context.card;let attempts=0;f.context.card=(...a)=>{if(++attempts===2)throw Error('Unlock UI fixture');card(...a);};assert.throws(()=>b.f(),/Unlock UI fixture/);const saved=JSON.stringify(f.s),draws=f.report().draws;f.context.card=card;b.f();assert.equal(JSON.stringify(f.s),saved);assert.equal(f.report().draws,draws);assert.equal(f.report().cards.length,2);assert.equal(f.report().done,1);});
const oldGame=execFileSync('git',['show','004cd26:docs/src/engine/game.js'],{encoding:'utf8',maxBuffer:20000000});
for(const [pos,role,ab] of [['P','SP',{vel:65,ctl:65,brk:65}],['P','MR',{vel:65,ctl:65,brk:65}],['IF',null,{con:65,pow:65,eye:65,spd:65}]])for(const rank of [0,1,2,3])for(const intlace of [false,true])test('old/new international RNG/stats '+[pos,role,rank,intlace].join('/'),()=>{const v={pos,role,ab,traits:{intlace},injNext:17},old=activeIntl(v,oldGame),now=activeIntl(v);for(const f of [old,now]){f.context.rank=rank;f.context.isSP=()=>role==='SP';f.run('POST');f.options()[0].f();}assert.equal(now.report().draws,old.report().draws);assert.deepEqual(now.s.intlStat,old.s.intlStat);assert.equal(now.s.injNext,old.s.injNext);assert.equal(now.s.intlCount,old.s.intlCount);assert.equal(now.s.pool,old.s.pool+(intlace&&rank===3?1:0));});
test('C09 actual active phaseEnd: champion, maintenance, salary/incentive/progression once',()=>{
  const s=state({tradeRefuse:2,tradeHeat:8,careerEarnings:111,careerBaseSalary:0,careerIncentive:0,yearlyIncentivePaid:{},yearOutsideIncome:111});
  s.ct=contracts.createContract({contractId:'champ',org:'NPB',teamId:s.orgTeamId,signedYear:2034,startYear:2035,years:2,annualSalary:100000000,incentive:createIncentiveTerms({org:'NPB',annualSalary:100000000})});
  champ.captureSeasonChampionship(s);let draws=0,moved=0,cards=0;
  const c={...champ,...contracts,applyIncentivePayment,classifyMarketInjury,S:s,phaseEnd:null,board:()=>{},migrateSalaryV140State:()=>{},teamRec:teamById,R:()=>{draws++;return 0;},escapeHTML:x=>x,card:()=>cards++,fmtMoney:x=>String(x),movement:()=>moved++,pendingOffseasonSalary:null,choose:()=>assert.fail('no pool'),allocUI:()=>{}};
  runInNewContext(game.slice(game.indexOf('  let seasonEndContext=null;'),game.indexOf('  movement = function()',game.indexOf('  let seasonEndContext=null;'))),c);
  c.phaseEnd();const saved=JSON.stringify(s);c.phaseEnd();assert.equal(JSON.stringify(s),saved);assert.deepEqual([draws,moved,cards],[1,1,2]);assert.equal(s.careerBaseSalary,100000000);assert.equal(s.careerEarnings,100000111);assert.deepEqual([s.tradeRefuse,s.tradeHeat],[1,3]);
});
test('snapshot placement and franchise hookup use unchanged actual path',()=>{assert.ok(game.indexOf('  captureSeasonChampionship(S);')>game.indexOf('  recordSalaryEvaluation(st);'));assert.ok(game.indexOf('  captureSeasonChampionship(S);')<game.indexOf('  tjGamble(()=>demotionAudit'));const source=game.slice(game.indexOf('function movement(){'),game.indexOf('function advance()'));assert.match(source,/S\.teamYears=\(S\.teamYears\|\|0\)\+1/);assert.match(source,/S\.teamYears>=7&&S\.champThisTeam&&S\.champTeam===S\.orgTeamId/);});
test('out-of-scope data and rules unchanged from latest dev',()=>{for(const file of ['src/data/event-cards-jp.js','src/data/jp-data.js','src/data/salary-market-data.js','src/engine/market-policy.js','src/engine/cross-league-market-policy.js','src/engine/contract-policy.js','src/engine/event-policy.js','src/engine/event-state-policy.js','src/engine/incentive-policy.js'])assert.equal(readFileSync(new URL('../docs/'+file,import.meta.url),'utf8').replace(/\r\n/g,'\n'),execFileSync('git',['show','004cd26:docs/'+file],{encoding:'utf8',maxBuffer:20000000}).replace(/\r\n/g,'\n'),file);});
console.log(`${cases} championship/international/migration/active integration checks PASS`);
