import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import os from 'node:os';
const root=fileURLToPath(new URL('../',import.meta.url)),arg=name=>process.argv.find(a=>a.startsWith('--'+name+'='))?.slice(name.length+3);
const {chromium}=createRequire(import.meta.url)(arg('playwright')||'playwright');
const hook=`\nwindow.__fix={get:()=>({state:JSON.parse(JSON.stringify(S)),rng:_s,calls:window.__rngCalls||0}),set:v=>Object.assign(S,v),draw:n=>drawEvents(n,()=>{window.__drawDone=(window.__drawDone||0)+1;}),board:p=>board(p),retire:()=>endGame('検証'),resolve:(id,mode,success)=>{const e=EVENTS.find(e=>e.id===id),p=beginEvent(S,e),r=applyEvent(S,e,mode,{chance:()=>{R();return success;},pick,abilityKeys:POS_AB[S.pos],occurrenceID:p.eventOccurrenceID});renderEventResult(e,r.result);return r.result;}};`;
const server=createServer(async(req,res)=>{try{const rel=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'index.html';if(rel.includes('..'))throw Error('path');let body=await readFile(path.join(root,'docs',rel));if(rel==='src/engine/game.js')body=body.toString().replace('function R(){','function R(){window.__rngCalls=(window.__rngCalls||0)+1;').replace('R = function(){','R = function(){window.__rngCalls=(window.__rngCalls||0)+1;')+hook;res.setHeader('Content-Type',rel.endsWith('.js')?'text/javascript; charset=utf-8':rel.endsWith('.css')?'text/css; charset=utf-8':'text/html; charset=utf-8');res.end(body);}catch(e){res.statusCode=404;res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const local=`http://127.0.0.1:${server.address().port}`,target=arg('preview')||local,shots=path.join(os.tmpdir(),'yakyujinsei-event-fix');await mkdir(shots,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[];
const wire=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('response',r=>{if(r.status()>=400&&/\.(js|css)(\?|$)/.test(r.url()))errors.push(r.status()+' '+r.url());});};
const start=async(p)=>{await p.goto(target+'/?seed='+encodeURIComponent('日本語 +?&%/#"'));await p.waitForFunction(()=>!document.querySelector('#btn-start').disabled);await p.locator('#btn-start').click();};
let failure;
try{
  for(const width of [1280,320,390]){
    const ctx=await browser.newContext({viewport:{width,height:844},isMobile:width<500,hasTouch:width<500}),p=await ctx.newPage();wire(p);await start(p);
    if(arg('preview'))for(const rel of ['index.html','src/config.js','src/engine/game.js','src/engine/event-state-policy.js','src/ui/seed-share.js','styles/seed-share.css']){
      const deployed=await p.evaluate(async rel=>{const r=await fetch('./'+rel,{cache:'no-store'});if(!r.ok)throw Error(rel+' HTTP '+r.status);return r.text();},rel);assert.equal(deployed.replace(/\r\n/g,'\n'),(await readFile(path.join(root,'docs',rel),'utf8')).replace(/\r\n/g,'\n'),rel+' differs from tested Preview source');
    }
    await p.evaluate(()=>{window.__copies=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.__copies.push(text)}});document.execCommand=()=>false;});
    const saved=arg('preview')?null:await p.evaluate(()=>window.__fix.get());
    await p.locator('#board-share').click();assert.equal(await p.locator('#share-seed-value').inputValue(),saved?.state.seed||'日本語 +?&%/#"');
    assert.match(await p.locator('#seed-share').innerText(),/同じSeedでも選択やバージョンが異なると結果は変わります/);
    await p.locator('#share-copy-seed').click();await p.waitForFunction(()=>document.querySelector('#seed-share-status').textContent==='Seedをコピーしました。');await p.locator('#share-copy-url').click();await p.waitForFunction(()=>document.querySelector('#seed-share-status').textContent==='リプレイURLをコピーしました。');
    const copied=await p.evaluate(()=>window.__copies),url=await p.locator('#share-url-value').inputValue();assert.deepEqual(copied,[saved?.state.seed||'日本語 +?&%/#"',url]);assert.equal(new URL(url).origin,target);assert.deepEqual([...new URL(url).searchParams.keys()],['seed']);assert.equal(new URL(url).hash,'');
    const replay=await ctx.newPage();wire(replay);await replay.goto(url);await replay.waitForFunction(()=>!document.querySelector('#btn-start').disabled);assert.equal(await replay.locator('#seed-show').inputValue(),saved?.state.seed||'日本語 +?&%/#"');assert.ok(await replay.locator('#btn-start').isVisible());await replay.close();
    for(const kind of ['missing','denied']){
      await p.evaluate(kind=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:kind==='missing'?undefined:{writeText:async()=>{throw Error('permission denied');}}}),kind);await p.locator('#share-copy-seed').click();await p.waitForFunction(()=>document.querySelector('#seed-share-status').textContent.startsWith('コピーできませんでした。'));assert.ok(await p.locator('#share-seed-value').isVisible());assert.equal(await p.locator('#share-seed-value').inputValue(),saved?.state.seed||'日本語 +?&%/#"');
    }
    await p.setViewportSize({width:width<500?844:1280,height:width<500?width:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.setViewportSize({width,height:844});await p.screenshot({path:path.join(shots,`${arg('preview')?'preview':'local'}-share-${width}.png`)});
    await p.locator('#seed-share-close').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'board-share');if(saved)assert.deepEqual(await p.evaluate(()=>window.__fix.get()),saved,'sharing changed S/RNG');
    await p.locator('#board-preferences').click();await p.locator('input[name="theme"][value="night"]').check();await p.locator('#preferences-close').click();await p.locator('#board-share').click();await p.keyboard.press('Shift+Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),'seed-share-close');await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.id),'share-seed-value');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'board-share');
    p.once('dialog',d=>d.dismiss());await p.locator('#btn-restart').click();if(saved)assert.deepEqual(await p.evaluate(()=>window.__fix.get()),saved,'settings/restart cancellation changed S/RNG');
    await p.evaluate(()=>{document.documentElement.dataset.fontSize='large';document.getElementById('bd-name').textContent='非常に長い選手名';document.getElementById('bd-team').textContent='長い球団名の福岡シーホークス（NPB二軍）';});
    const boxes=await p.evaluate(()=>['bd-name','bd-team','btn-restart','board-preferences','board-share'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};}));for(const b of boxes){assert.ok(b.width>0&&b.right<=width,b.id+' hidden/overflow');if(b.id.includes('board-')||b.id==='btn-restart')assert.ok(b.width>=44&&b.height>=44);}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.right<=b.x||b.right<=a.x||a.bottom<=b.y||b.bottom<=a.y,'header overlap');}await p.evaluate(()=>document.documentElement.dataset.fontSize='medium');
    if(!arg('preview')){
      for(const [stage,lv,org] of [['HS','HS','AMATEUR'],['U','U','AMATEUR'],['CORP','CORP','CORP'],['PRO','NPB1','NPB']])for(const phase of [0,1,2]){
        await p.evaluate(v=>{window.__fix.set({...v,year:2035});window.__fix.board(v.phase);}, {stage,lv,org,phase});const before=await p.evaluate(()=>window.__fix.get());await p.locator('#board-share').click();assert.equal(await p.locator('#share-seed-value').inputValue(),before.state.seed);await p.keyboard.press('Escape');assert.deepEqual(await p.evaluate(()=>window.__fix.get()),before);
      }
      const outputs=await p.evaluate(async()=>{const {EVENT_CATALOG}=await import('./src/data/event-cards-jp.js');const e=EVENT_CATALOG.events.find(e=>e.category==='training'&&e.eligibility.role==='ALL'),out=[];for(const traits of [{},{clutch:true},{clutch:true,genius:true}])for(const success of [true,false]){window.__fix.set({year:2035,pos:'P',stage:e.eligibility.stages[0],lv:e.eligibility.levels[0],org:e.eligibility.orgs[0],age:23,traits,ab:{vel:55,ctl:55,brk:55,sta:55},pot:{vel:80,ctl:80,brk:80,sta:80},carry:{vel:1,ctl:1,brk:1,sta:1},pendingEvent:null});const result=window.__fix.resolve(e.id,'bold',success);out.push({result,text:document.querySelector('[data-event-occurrence-id="'+result.eventOccurrenceID+'"]').innerText});}return out;});
      for(const {result:r,text} of outputs){assert.ok(text.includes('勝負'+(r.success?'成功':'失敗')));assert.ok(text.includes(r.abilityPoints>0?'獲得育成点 +'+r.abilityPoints:'適用育成点 '+r.abilityPoints));assert.ok(text.includes('育成点繰越 '+r.ability.carryBefore+' → '+r.ability.carryAfter));}
      const categories=await p.evaluate(async()=>{const {EVENT_CATALOG}=await import('./src/data/event-cards-jp.js'),out=[];for(const [category,stage,mode] of [['encounter','HS','bold'],['encounter','PRO','bold'],['endorsement','PRO','safe'],['endorsement','PRO','bold']]){const e=EVENT_CATALOG.events.find(e=>e.category===category&&e.eligibility.role==='ALL'&&e.eligibility.stages.includes(stage));const lv=stage==='HS'?'HS':e.eligibility.levels.find(l=>!['HS','U','CORP','IND'].includes(l)),org=stage==='HS'?'AMATEUR':lv==='MLB'?'MLB':['R','A1','A2','A3'].includes(lv)?'MiLB':lv.split('_')[0].replace(/[12]$/,'');window.__fix.set({year:2035,pos:'P',stage,lv,org,age:23,traits:{},ab:{vel:55,ctl:55,brk:55,sta:55},pot:{vel:80,ctl:80,brk:80,sta:80},carry:{},pendingEvent:null});const result=window.__fix.resolve(e.id,mode,true);out.push({result,text:document.querySelector('[data-event-occurrence-id="'+result.eventOccurrenceID+'"]').innerText});}return out;});
      assert.equal(categories[0].result.category,'training');assert.match(categories[0].text,/獲得育成点 \+3/);assert.doesNotMatch(categories[1].text,/獲得育成点|育成点繰越/);assert.match(categories[1].text,/今季成績点\+3/);assert.doesNotMatch(categories[2].text,/獲得育成点|育成点繰越/);assert.match(categories[2].text,/スポンサー収入/);assert.match(categories[3].text,/獲得育成点 \+1/);assert.match(categories[3].text,/スポンサー収入/);
      await p.screenshot({path:path.join(shots,'results-'+width+'.png')});
      // Three actual draws and listeners in one year must keep distinct fixed IDs.
      await p.evaluate(()=>{window.__fix.set({year:2036,pos:'P',stage:'HS',lv:'HS',org:'AMATEUR',age:23,traits:{},pendingEvent:null,eventDrawYear:2036,eventDrawnCardIDs:[],ab:{vel:55,ctl:55,brk:55,sta:55},pot:{vel:80,ctl:80,brk:80,sta:80},carry:{},pendStat:0});window.__fix.draw(3);});
      const drawn=[];for(let i=0;i<3;i++){await p.locator('#act button').click();drawn.push((await p.evaluate(()=>window.__fix.get())).state.pendingEvent.cardID);await p.locator('#act button').last().click();}assert.equal(new Set(drawn).size,3);assert.equal(await p.evaluate(()=>window.__drawDone),1);const drawnState=await p.evaluate(()=>window.__fix.get());assert.deepEqual(drawnState.state.eventDrawnCardIDs,drawn);
      // Exhaust the actual pool. No redraw, loop or extra RNG after it becomes empty.
      await p.evaluate(async()=>{const {EVENT_CATALOG}=await import('./src/data/event-cards-jp.js'),{eventEligible}=await import('./src/engine/event-policy.js');window.__fix.set({year:2035,pos:'IF',stage:'PRO',lv:'NPB1',org:'NPB',age:23,traits:{favorite:false,adking:false},eventDrawYear:2035,eventDrawnCardIDs:[]});const s=window.__fix.get().state,ids=EVENT_CATALOG.events.filter(e=>eventEligible(e,s)).map(e=>e.id);window.__fix.set({eventDrawnCardIDs:ids});window.__fix.draw(3);});const beforeEmpty=await p.evaluate(()=>window.__fix.get());await p.locator('#act button').click();assert.equal(await p.evaluate(()=>window.__drawDone),2);assert.deepEqual(await p.evaluate(()=>window.__fix.get()),beforeEmpty);assert.match(await p.locator('#log').innerText(),/今年まだ引いていない/);
      await p.evaluate(()=>window.__fix.retire());await p.locator('#board-share').click();assert.equal(await p.locator('#share-seed-value').inputValue(),saved.state.seed);await p.keyboard.press('Escape');await p.locator('#sh-img').click();await p.locator('#sh-out img').waitFor();const beforeRetCopy=await p.evaluate(()=>window.__fix.get());await p.locator('#sh-url').click();await p.locator('#sh-out input').waitFor();assert.equal(await p.locator('#sh-out input').inputValue(),url);assert.deepEqual(await p.evaluate(()=>window.__fix.get()),beforeRetCopy,'existing retirement copy changed S/RNG');
    }
    await ctx.close();console.log(`${arg('preview')?'Preview':'Local'} ${width}: sharing/seed-only URL/clipboard fallbacks/focus/header/rotation and ${arg('preview')?'deployed UI':'event points/exhaustion/all phases/read-only RNG/retirement'} passed`);
  }
  assert.deepEqual(errors,[]);console.log('Console/JS-CSS404: 0; screenshots '+shots);
}catch(e){failure=e;console.error(e.stack);}finally{server.closeAllConnections();server.close();await Promise.race([browser.close(),new Promise(r=>setTimeout(r,5000))]);process.exit(failure?1:0);}
