import assert from 'node:assert/strict';
import { appendSalaryDecision, buildSalaryDecision, deriveSalaryReasonCodes, salaryReasonLabel } from '../docs/src/engine/salary-explanation-policy.js';

const base={decisionYear:2027,salaryYear:2028,decisionType:'PROMOTION',sourceLevel:'NPB2',targetLevel:'NPB1',previousSalary:12_000_000,finalSalary:18_000_000,sourceMarketRating:5.2,convertedMarketRating:-0.8,baseSalary:16_000_000,contractMultiplier:1,positionMultiplier:1.05,decreaseProtectionApplied:true,marketComponents:[{year:2027,payD:6,normalizedWeight:1,contribution:6}],currentEvaluation:{baseD:3.2,performanceAdjustment:1.4,workloadAdjustment:.3,awardAdjustment:.35,payD:5.25,source:'ACTUAL_PERFORMANCE'}};
const raised=buildSalaryDecision(base);
assert.equal(raised.changeAmount,6_000_000);assert.equal(raised.changeRate,.5);
assert.ok(raised.reasonCodes.includes('STRONG_PERFORMANCE'));assert.ok(raised.reasonCodes.includes('FULL_WORKLOAD'));assert.ok(raised.reasonCodes.includes('AWARD_BONUS'));assert.ok(raised.reasonCodes.includes('LEVEL_PAR_DOWNWARD_CONVERSION'));assert.ok(raised.reasonCodes.includes('PREMIUM_POSITION'));assert.ok(raised.reasonCodes.includes('NO_DECREASE_PROTECTION'));assert.ok(raised.reasonCodes.includes('ONE_YEAR_MARKET_SAMPLE'));
const lowered=deriveSalaryReasonCodes({...base,currentEvaluation:{performanceAdjustment:-.75,workloadAdjustment:-.5,awardAdjustment:0},sourceMarketRating:2,convertedMarketRating:3,positionMultiplier:.9,contractMultiplier:.8,decreaseProtectionApplied:false,marketComponents:[{},{}]});
assert.ok(lowered.includes('POOR_PERFORMANCE'));assert.ok(lowered.includes('LIMITED_WORKLOAD'));assert.ok(lowered.includes('LEVEL_PAR_UPWARD_CONVERSION'));assert.ok(lowered.includes('DH_DISCOUNT'));assert.ok(lowered.includes('CONTRACT_DISCOUNT'));
const floorDecision=buildSalaryDecision({...base,previousSalary:16_000_000,finalSalary:16_000_000,floorApplied:true,currentEvaluation:{performanceAdjustment:-1,workloadAdjustment:-.5,awardAdjustment:0}});assert.equal(floorDecision.floorApplied,true);assert.equal(floorDecision.reasonCodes[0],'LEAGUE_MINIMUM_APPLIED');assert.ok(floorDecision.reasonCodes.includes('POOR_PERFORMANCE'));assert.equal(salaryReasonLabel('LEAGUE_MINIMUM_APPLIED'),'リーグ最低年俸が適用されました');
const ordinaryCut=buildSalaryDecision({...base,previousSalary:20_000_000,finalSalary:18_000_000,floorApplied:false,currentEvaluation:{performanceAdjustment:-1,workloadAdjustment:0,awardAdjustment:0}});assert.ok(ordinaryCut.reasonCodes.includes('POOR_PERFORMANCE'));assert.ok(!ordinaryCut.reasonCodes.includes('LEAGUE_MINIMUM_APPLIED'));
assert.equal(buildSalaryDecision({...base,previousSalary:0}).changeRate,null);
assert.equal(new Set(deriveSalaryReasonCodes({...base,positionMultiplier:1.2,contractMultiplier:1.2})).size,deriveSalaryReasonCodes({...base,positionMultiplier:1.2,contractMultiplier:1.2}).length);
assert.equal(salaryReasonLabel('UNKNOWN_CODE'),'その他の契約条件');
let history=[];for(let i=24;i>=0;i--)history=appendSalaryDecision(history,buildSalaryDecision({...base,salaryYear:2029+i,decisionYear:2028+i,decisionType:'RENEWAL'}));
assert.equal(history.length,25);assert.equal(history[0].salaryYear,2029);
assert.deepEqual(history.map(item=>item.salaryYear),Array.from({length:25},(_,i)=>2029+i));
const snapshot=structuredClone(history);
history=appendSalaryDecision(history,buildSalaryDecision({...base,salaryYear:2035,decisionYear:2034,decisionType:'RENEWAL',finalSalary:99}));
assert.equal(history.length,25);assert.equal(history.find(item=>item.salaryYear===2035).finalSalary,99);
history=appendSalaryDecision(history,buildSalaryDecision({...base,salaryYear:2035,decisionYear:2034,decisionType:'PROMOTION'}));
assert.equal(history.length,26);assert.deepEqual(history.filter(item=>item.salaryYear===2035).map(item=>item.decisionType),['RENEWAL','PROMOTION']);
assert.deepEqual(snapshot[0],history[0]);assert.equal(snapshot.find(item=>item.salaryYear===2035).finalSalary,base.finalSalary);
assert.equal(appendSalaryDecision(undefined,raised).length,1);
console.log('salary explanation policy tests passed');
